In [1]:
import numpy as np
import random

In [2]:
num_individuos = 1000 # Quantidade de individuos por geração
populacao_inicial = np.zeros((num_individuos, 8), dtype = int) # Gera população vazia

for i in range(num_individuos):
    for j in range(8):
        populacao_inicial[i][j] = random.randint(1,8) # Gera população com posições das rainhas aleatórias

print("População Inicial:")
for i in range(num_individuos):
    print(populacao_inicial[i])

População Inicial:
[3 8 4 5 8 5 8 8]
[6 6 8 3 8 8 1 1]
[2 5 7 2 1 1 8 2]
[3 8 8 2 4 6 4 8]
[5 8 5 8 3 1 5 7]
[8 6 1 7 7 1 3 1]
[8 3 2 1 1 1 5 8]
[5 5 7 8 1 8 5 8]
[5 8 4 5 7 7 5 2]
[4 2 3 4 7 2 6 3]
[7 6 3 8 3 6 8 6]
[7 5 4 2 7 6 6 1]
[2 7 1 4 5 7 4 8]
[2 4 7 7 5 7 5 7]
[6 1 2 5 4 8 1 5]
[8 1 1 5 2 2 2 3]
[5 3 3 1 2 2 8 4]
[3 1 6 7 3 2 6 1]
[8 4 6 6 8 4 4 7]
[4 5 6 7 7 2 8 8]
[7 2 4 3 6 2 2 1]
[2 7 7 4 7 6 2 1]
[4 5 4 1 7 6 6 3]
[2 3 8 4 5 5 3 5]
[6 4 7 7 8 7 4 5]
[3 1 2 6 5 4 1 7]
[4 8 6 4 6 7 1 1]
[4 6 5 2 8 4 7 2]
[8 7 6 8 7 5 8 5]
[2 4 6 5 2 2 3 1]
[5 7 1 5 6 2 8 6]
[3 6 1 5 2 6 4 1]
[8 4 2 1 2 4 2 4]
[2 1 8 8 7 7 2 3]
[7 7 6 8 8 7 1 4]
[2 6 7 1 7 2 1 5]
[1 2 6 6 7 7 1 6]
[8 6 3 7 3 7 2 1]
[2 4 8 3 5 3 5 8]
[5 2 3 5 8 8 8 2]
[4 8 5 5 7 2 1 2]
[6 6 1 4 6 8 7 7]
[6 7 8 8 6 8 8 8]
[4 1 3 3 4 6 4 8]
[5 4 4 2 6 6 4 5]
[3 4 4 2 1 6 1 2]
[7 8 5 8 4 6 3 4]
[5 6 3 5 4 7 5 6]
[3 1 3 1 5 5 7 3]
[5 2 3 5 4 6 7 5]
[6 2 4 2 4 3 5 2]
[6 7 2 3 3 8 1 7]
[4 3 6 4 5 8 7 7]
[4 6 5 6 1 3 7 8]
[7 4 7 3 

In [3]:
def fitness(individuo):
    pares_atk = 0 # numero de pares de rainhas que se atacam
    for i in range(8):
        for j in range(8):
            if(i != j):
                if((individuo[i] == individuo[j])or(checar_diagonal(individuo,i,j))): #testa se estão na mesma linha ou na mesma diagonal
                    pares_atk +=1
    f = pares_atk
    return f
                   
def checar_diagonal(individuo,i,j):
    if(abs(i-j) == abs(individuo[i]-individuo[j])): #testa se eles estão em uma diagonal comum
        return True
    return False
    
def retorna_fit_pop(populacao):
    fit_pop = [] # vetor que armazena o fitness de cada individuo  
    for i in range(num_individuos):
        fitness_individuo = fitness(populacao[i])
        fit_pop.append(fitness_individuo)
    return fit_pop

In [4]:
def selecao_torneio(fit_pop):
    individuo_1 = -1
    individuo_2 = -1
    # Ganha o duelo aquele que tiver o menor fitness
    while(individuo_1 == individuo_2):
        # Primeira Vaga 
        contenders = random.sample(range(0, num_individuos), 2)
        if(fit_pop[contenders[0]] < fit_pop[contenders[1]]):
            individuo_1 = contenders[0]
        else:
            individuo_1 = contenders[1]
        
        # Segunda Vaga
        contenders = random.sample(range(0, num_individuos), 2)
        if(fit_pop[contenders[0]] < fit_pop[contenders[1]]):
            individuo_2 = contenders[0]
        else:
            individuo_2 = contenders[1]
       
    return individuo_1,individuo_2 

In [5]:
def cruzamento(individuo,populacao):
    ponto_cruzamento = random.randint(1,7) #sortea uma posição do vetor para realizar cruzamento(inicio e fim do vetor desconsiderados para evitar clones)
    pais_1 = populacao[individuo[0]]
    pais_2 = populacao[individuo[1]]
    
    #Cruzamento no ponto 
    filhos_1 = np.concatenate([pais_1[:ponto_cruzamento],pais_2[ponto_cruzamento:]])
    filhos_2 = np.concatenate([pais_2[:ponto_cruzamento],pais_1[ponto_cruzamento:]])
    return filhos_1, filhos_2

In [6]:
def mutacao(filhos, taxa):
    for i in range(len(filhos)):
        if random.random() < taxa: # caso o número sorteado esteja dentro da taxa ele realiza mutação
            pos = random.randint(0, 7) # sortea qual coluna terá o valor mutado
            filhos[i][pos] = random.randint(1,8) # atribui um número aleatório para a linha 

    return filhos

In [7]:
def elitismo(fit_pop):

    individuo_1 = fit_pop.index(min(fit_pop)) # extrai o melhor individuo
    fit_pop.pop(individuo_1) # retira o melhor individuo da amostra
    individuo_2 = fit_pop.index(min(fit_pop)) # extrai o segundo melhor individuo

    return individuo_1,individuo_2

In [8]:
# faz o ciclo das gerações até encontrar uma solução
contagem_geracoes = 0 # conta quantas gerações foram necessárias para se encontrar solução  
while(1):

    nova_populacao = np.zeros((num_individuos, 8), dtype=int) # Nova populacao vazia

    fit = retorna_fit_pop(populacao_inicial)  # Calcula o fitness da população

  # Imprime o melhor da geração
    melhor_individuo = fit.index(min(fit))
    print("Melhor da geração:", populacao_inicial[melhor_individuo],"Fitness:",fit[melhor_individuo])
    print()
    
     
  # Verifica se encontrou solução
    if(fit[melhor_individuo] == 0):
        print("Solução Encontrada","em", contagem_geracoes+1,"gerações:")
        print(populacao_inicial[melhor_individuo]) # imprime a solução
        break # se encontrou solução encerra o processo
    
  # Elitismo
    elite = elitismo(fit.copy()) 
    nova_populacao[0] = populacao_inicial[elite[0]]
    nova_populacao[1] = populacao_inicial[elite[1]]

  # Gera os filhos restantes para completar a população
    num_filhos = 2
    while num_filhos < num_individuos:

        ind_vencedores = selecao_torneio(fit) # Seleção por torneio
    
        filhos = cruzamento(ind_vencedores,populacao_inicial) # Cruzamento

        filhos = mutacao(filhos, 0.0075) # Mutação (taxa de 7,5%)

        # Coloca os filhos na nova população
        nova_populacao[num_filhos] = filhos[0]
        nova_populacao[num_filhos+1] = filhos[1]

        # Aumenta o número de filhos
        num_filhos = num_filhos + 2

    # Substitui a populacao antiga pela atual
    populacao_inicial = nova_populacao.copy()
    contagem_geracoes += 1
    


Melhor da geração: [6 6 1 1 7 5 2 8] Fitness: 4

Melhor da geração: [6 6 1 1 7 5 2 8] Fitness: 4

Melhor da geração: [6 6 1 1 7 5 2 8] Fitness: 4

Melhor da geração: [6 6 1 1 7 5 2 8] Fitness: 4

Melhor da geração: [6 7 2 4 1 8 5 3] Fitness: 2

Melhor da geração: [6 7 2 4 1 8 5 3] Fitness: 2

Melhor da geração: [6 7 2 4 1 8 5 3] Fitness: 2

Melhor da geração: [6 7 2 4 1 8 5 3] Fitness: 2

Melhor da geração: [6 7 2 4 1 8 5 3] Fitness: 2

Melhor da geração: [6 7 2 4 1 8 5 3] Fitness: 2

Melhor da geração: [6 4 2 8 5 7 1 3] Fitness: 0

Solução Encontrada em 11 gerações:
[6 4 2 8 5 7 1 3]
